[build]
builder = "dockerfile"
dockerfilePath="./ShopeeKorean/Dockerfile"

[deploy]
startCommand = "dotnet ShopeeKorean.Application.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 120
