[build]
builder = "dockerfile"
dockerfilePath = "ShopeeKorean/Dockerfile"

[deploy]
startCommand = "dotnet ShopeeKorean.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 120
