databases:
  - name: shopee-db
    databaseName: shopee
    user: postgres
    plan: free  # PostgreSQL miễn phí

services:
  - type: web
    name: shopee-korean-dotnet-backend
    runtime: docker # Hoặc docker nếu dùng .NET Core
    envVars:
      - key: ConnectionStrings__Default
        fromDatabase:
          name: shopee-db
          property: connectionString